### ISSUE TITLE
T8A3 feedback

### ISSUE THREAD

**Issue by nirandiw** [CS2103AUG2016-T11-C2/main#32]
### User Guide

- Where is the command summary in the user guide? Add it quickly Your user guide must be complete by now. 

### User stories

- The ability to specify a specific folder as the data storage location is a must have feature. Please cover that in the user stories and add the necessary commands. 

- Please go through the product must have feature to make sure you have not missed anything else.

### Use cases
-  The steps in MSS are not properly aligned for uses cases add task, Mark task as done. Fix it.

### NFR
-  The module handbook has a lot of project constraints which can be taken as NFRs. May be add a hyperlink to it. 

### Product survey

- Not enough. You need to list the Strengths and Weakness separately under a heading. You need to survey more products. At least 4.

**Comment by cheo1994** [comment]
Thank You so much!
